### PR TITLE
RetroMusicPlayer: Update to v4.0.010_1012202047.

### PR DESCRIPTION
**Pull request by hadad**
Source: https://github.com/h4h13/RetroMusicPlayer/releases/tag/v4.0

Changelogs:
* Re-built from scratch using MVVM Architecture and JetPack Components
* New Material Design icon
* Implemented a custom database for playlist
* Added new Material Design motions
* Bug fixes & performance improvements
* Revamped Home tab UI
* Android 11 support
* And more!

### CODE REVIEW

**Comment by goodmeow** [comment]
0mb?

**Comment by hadad** [comment]
> 0mb?

Ngga, coba view file di commit

**Comment by wulan17** [comment]
@hadad Lah empty file

**Comment by hadad** [comment]
> @hadad Lah empty file

Njirr, ni kalo di raw ada

https://github.com/Komodo-OS-Rom/vendor_komodo/raw/3f04a706ffc4f00cc7165dfee67b3baec27fc038/prebuilt/app/RetroMusicPlayer/RetroMusicPlayer.apk

**Pull request merged**
